codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  status:
    project:
      default:
        target: 10%
        threshold: 0%
    patch:
      default:
        target: 10%
        threshold: 0%

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

github_checks:
  annotations: true
